8_Security_Defending_WebApplication/Exercises/LearningSystem.Web/LearningSystem.Web/Controllers/CoursesController.cs
namespace LearningSystem.Web.Controllers
{
    using LearningSystem.Data;
    using LearningSystem.Data.Models;
    using LearningSystem.Services.Home.Interfaces;
    using LearningSystem.Services.Home.Models;
    using LearningSystem.Web.Infrastructures.Extensions;
    using LearningSystem.Web.Models.Courses;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class CoursesController : Controller
    {
        private readonly ICourseService courses;
        private readonly UserManager<User> userManager;

        public CoursesController(ICourseService courses, UserManager<User> userManager)
        {
            this.courses = courses;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Details(int courseId)
        {
            var model = new CourseDetailsViewModel
            {
                Course = await this.courses.CourseByIdAsync<CourseDetailsServiceModel>(courseId),
            };

            if (model.Course == null)
            {
                return NotFound();
            }

            if (User.Identity.IsAuthenticated)
            {
                var userId = this.userManager.GetUserId(User);

                model.UserIsSignedInCourse = await this.courses.UserIsSignedInCourse(courseId, userId);
            }

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SignIn(int id)
        {
            var userId = this.userManager.GetUserId(User);

            var result = await this.courses.SignInUser(id, userId);

            if (!result)
            {
                return NotFound();
            }
            TempData.AddSuccessMessage("You are signed In to this course!");

            return RedirectToAction(nameof(Details), new { id });
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SignOut(int id)
        {
            var userId = this.userManager.GetUserId(User);

            var result = await this.courses.SignOutUser(id, userId);

            if (!result)
            {
                return NotFound();
            }
            TempData.AddSuccessMessage("Sorry to your sign out!");

            return RedirectToAction(nameof(Details), new { id });
        }

        //--------------------------Exam------------------------------------------

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SubmitExam(int courseId, IFormFile exam)
        {
            if (!exam.FileName.EndsWith(".zip") || exam.Length > DataConstants.CoursesExamSubmissionFileLenght || exam == null)
            {
                TempData.AddErrorMessage("Your file should be a '.zip' file with mx 2 MB in size!");
                //ModelState.AddModelError(string.Empty, "Your file should be a '.zip' file with mx 2 MB in size!");

                return RedirectToAction(nameof(Details), new { courseId });
            }

            //using (var memoryStream = new MemoryStream())
            //{
            //    await exam.CopyToAsync(memoryStream);
            //}

            var fileExamSolutionContents = await exam.ToByteArrayAsync();

            var userId = this.userManager.GetUserId(User);

            var success = await this.courses.SaveExamSubmission(courseId, userId, fileExamSolutionContents);

            if (!success)
            {
                return BadRequest();
            }

            TempData.AddSuccessMessage("Exam submission saved successfully!");

            return RedirectToAction(nameof(Details), new { courseId });
        }
    }
}

8_Security_Defending_WebApplication/Exercises/LearningSystem.Web/LearningSystem.Web/Controllers/TrainerController.cs
namespace LearningSystem.Web.Controllers
{
    using LearningSystem.Data.Models;
    using LearningSystem.Services.Home.Interfaces;
    using LearningSystem.Services.Home.Models;
    using LearningSystem.Web.Infrastructures.Extensions;
    using LearningSystem.Web.Models.Trainer;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Threading.Tasks;

    [Authorize(Roles = WebConstants.TrainerRole)]
    public class TrainerController: Controller
    {
        private readonly ITrainerService trainer;
        private readonly ICourseService courses;
        private readonly UserManager<User> userManager;

        public TrainerController(ITrainerService trainer, UserManager<User> userManager, ICourseService courses)
        {
            this.trainer = trainer;
            this.userManager = userManager;
            this.courses = courses;
        }

        public  async Task<IActionResult> Courses()
        {
            var userId = this.userManager.GetUserId(User);

            var courses = await this.trainer.Courses(userId);

            return View(courses);
        }

        public async Task<IActionResult> Students(int courseId)
        {
            var userId = this.userManager.GetUserId(User);

            if (!await this.trainer.IsTrainer(courseId, userId))
            {
                return NotFound();
            }
         
            return View(new StudentsInCourseViewModel
            {
                Students = await this.trainer.StudentsInCourse(courseId),
                Course =  await this.courses.CourseByIdAsync<CoursesListingServiceModel>(courseId)
            });
        }

        [HttpPost]
        public async Task<IActionResult> GradeStudent(int courseId, string studentId, Grade grade)
        {
            if (studentId == null)
            {
                return BadRequest();
            }

            var userId = this.userManager.GetUserId(User);

            if (!await this.trainer.IsTrainer(courseId, userId))
            {
                return BadRequest();
            }

            var success = await this.trainer.AddGrade(courseId, studentId, grade);

            if (!success)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Students), new { courseId});
        }

        public async Task<IActionResult> DownloadExam(int courseId, string studentId)
        {
            if (studentId == null)
            {
                return BadRequest();
            }
            var studentName = this.userManager.FindByIdAsync(studentId);

            var userId = this.userManager.GetUserId(User);

            if (!await this.trainer.IsTrainer(courseId, userId))
            {
                return BadRequest();
            }

            var studentInCourseNames = await this.trainer.StudentInCourseNames(courseId, studentId);

            if (studentInCourseNames == null)
            {
                return BadRequest();
            }

            var examSolutionSubmission = await this.trainer.GetExamSolutionSubmission(courseId, studentId);

            if (examSolutionSubmission == null)
            {
                TempData.AddErrorMessage($"No available exam solution from {studentInCourseNames.UserName}");
                return RedirectToAction(nameof(Students), new { courseId });
            }
            
            return File(examSolutionSubmission, "application/zip", $"{studentInCourseNames.CourseTitle}-{studentInCourseNames.UserName}-{DateTime.Now}.zip");
        }
    }
}

8_Security_Defending_WebApplication/Exercises/LearningSystem.Web/LearningSystem.Web/Controllers/UsersController.cs
namespace LearningSystem.Web.Controllers
{
    using LearningSystem.Data.Models;
    using LearningSystem.Services.Home.Interfaces;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;

    public class UsersController:Controller
    {
        private readonly IUserService users;
        private readonly UserManager<User> userManager;

        public UsersController(IUserService users, UserManager<User> userManager)
        {
            this.users = users;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Profile(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);

            if (user == null)
            {
                return NotFound();
            }

            var profile = await this.users.ProfileAsync(user.Id);

            return View(profile);
        }

        [Authorize]
        public async Task<IActionResult> DownloadSertificate(int courseId)
        {
            var userId = this.userManager.GetUserId(User);

            var certificateContents = await this.users.GetPdfCertificate(courseId, userId);

            if (certificateContents == null)
            {
                return BadRequest();
            }

            return File(certificateContents, "application/pdf", "Certificate.pdf");
        }
    }
}

8_Security_Defending_WebApplication/Exercises/LearningSystem.Web/LearningSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LearningSystem</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LearningSystem</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="Blog" asp-controller="Articles" asp-action="Index">Blog</a></li>
                    @if (User.IsInRole(WebConstants.AdministratorRole))
                    {
                      <li style="margin-left:10px;margin-right:10px;text-align:center">
                        <table>
                            <tr>
                                <th colspan="2">
                                    <li><h4 style="color:red; text-align:center">Admin area</h4></li>  
                                </th>
                            </tr>
                            <tr>
                                <th>
                                     <li style="margin-left:5px;margin-right:10px; text-align:center"><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
                                </th>
                                <th>
                                    <li class="dropdown" style="margin-left:5px;margin-right:10px;text-align:center">
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            Courses
                                        <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a asp-area="Admin" asp-controller="Courses" asp-action="Create">Create Course</a></li>
                                            <li><a asp-area="Admin" asp-controller="Courses" asp-action="Delete">Delete Course</a></li>
                                        </ul>
                                    </li>
                                </th>
                            </tr>
                        </table>
                      </li>
                        
                    }
                    @if (User.IsInRole(WebConstants.TrainerRole))
                    {
                      <li style="margin-left:10px;margin-right:10px;text-align:center">
                        <table>
                            <tr>
                                <th>
                                    <li><h4 style="color:deepskyblue">Trainer area</h4></li>  
                                </th>
                            </tr>
                            <tr>
                                <th>
                                    <li style="text-align:center" >
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            Trainer
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a asp-area="" asp-controller="Trainer" asp-action="Courses">Trainer Courses</a></li>
                                        </ul>
                                    </li>
                                </th>
                            </tr>
                        </table>
                      </li>
                    }
                    @if (User.IsInRole(WebConstants.BlogAuthorRole))
                    {
                      <li style="margin-left:10px;margin-right:10px; text-align:center">
                        <table>
                            <tr>
                                <th>
                                    <li><h4 style="color:yellow; align-content:center">Blogauthor area</h4></li>
                                </th>
                            </tr>
                            <tr>
                                <th>
                                    <li style="text-align:center" >
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            Blogauthor
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a asp-area="Blog" asp-controller="Articles" asp-action="Create">Publish Article</a></li>
                                        </ul>
                                    </li>
                                </th>
                            </tr>
                        </table>          
                      </li>            
                     }
                    @*@if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Profile" asp-route-username=@($"{User.Identity.Name}")>My Profile</a></li>
                    }*@
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <br />
    <br />
    <div class="container body-content">
        @if (TempData.ContainsKey(WebConstants.TempdataSuccessMessageKey))
        {
            <div class="alert alert-success">
                @TempData[WebConstants.TempdataSuccessMessageKey]
            </div>
        }
        @if (TempData.ContainsKey(WebConstants.TempDataErrorMessageKey))
        {
            <div class="alert alert-danger">
                @TempData[WebConstants.TempDataErrorMessageKey]
            </div>
        }    
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - LearningSystem</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>